Switch print_error to error_out when run_cmd is missing
Without this, if you try 'ttc pb2 run something something" you get
the exception below from do_run()

Error: run_cmd not configured for target pb2
Traceback (most recent call last):
  File "/usr/local/bin/ttc", line 2238, in <module>
    main()
  File "/usr/local/bin/ttc", line 2177, in main
    do_run(tmap, options)
  File "/usr/local/bin/ttc", line 966, in do_run
    dprint("os.execvp(%s, %s)" % (exec_args[0], exec_args))
IndexError: list index out of range

Fix this exception by using error_out() instead.

Signed-off-by: Tim Bird <tim.bird@sony.com>